#!/usr/bin/env bash

# Automatically generate the protobuf messages defined
#   in the src/protos

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

SCRIPT="$(realpath "$0")"
BASEDIR="$(dirname "${SCRIPT}")"

pushd "./src/toybox_msgs" >>/dev/null|| exit

DIRS=($(find ./protos/ -type d -printf '%P\n'))
for directory in "${DIRS[@]}"; do

    echo "---------------------------------------------------"
    echo "Building protos from <${directory}> ..."
    IN_DIR="${BASEDIR}/src/toybox_msgs/protos/${directory}/"
    OUT_DIR="${BASEDIR}/src/toybox_msgs/"

    mkdir -p "${OUT_DIR}"

    python3 -m grpc_tools.protoc \
            --proto_path="${BASEDIR}/src/toybox_msgs/protos/" \
            --python_out="${OUT_DIR}" \
            --grpc_python_out="${OUT_DIR}" \
            --pyi_out="${OUT_DIR}" \
            ${IN_DIR}/*.proto
    
    # protoc won't use relative imports for *_grpc.py files, for some reason,
    # so we're modifying them in place here to explicity import from "toybox_msgs.*"
    for file in "${OUT_DIR}/${directory}"/*pb2*.py; do
        sed -E -i -e 's|^from ([A-Za-z0-9_]*) import|from toybox_msgs.\1 import|g' "${file}"
    done

    echo "---------------------------------------------------"

done


popd >>/dev/null || exit