#!/usr/bin/env bash

# Automatically generate the protobuf messages defined
#   in the subdirectories of toybox_msgs

SCRIPT="$(realpath "$0")"
BASEDIR="$(dirname "${SCRIPT}")"
echo "${BASEDIR}"

for directory in */; do

    IN_DIR="${BASEDIR}/${directory}/proto"
    OUT_DIR="${BASEDIR}/${directory}"

    # if a directory has it's own build_messages exec, just do that
    if [[ -x "${directory}/build_messages" ]]; then
        "${directory}/build_messages"
    else
        [[ "${directory}" == "build" ]] && continue
        [[ ! -d "${IN_DIR}" ]] && continue

        if [[ ! -d "${OUT_DIR}" ]]; then
            mkdir -p "${OUT_DIR}"
        fi
        
        cp initpy.txt "${OUT_DIR}/__init__.py"

        echo "Building messages in ${IN_DIR}"
        # protoc -I="${IN_DIR}" \
        #     --python_out="${OUT_DIR}" \
        #     ${IN_DIR}/*.proto
        python3 -m grpc_tools.protoc \
            -I="${IN_DIR}" \
            --python_out="${OUT_DIR}" \
            ${IN_DIR}/*.proto
    fi

done