[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "toybox_msgs"
version = "0.0.1"
authors = [
    {name="Wes Fletcher", email="please@donot.com"},
]
description = "Simple (toy) robotics stack messages"
readme = "README.md"
requires-python = ">=3.8"
classifiers = []

[project-urls]
"Homepage" = "https://github.com/wesfletch/toybox"

[tools.setuptools]
packages=["toybox_msgs",
          "toybox_msgs.primitive",
          "toybox_msgs.state",
          "toybox_msgs.core"]