#!/usr/bin/env bash

# A special build_messages script that handles gRPC.

SCRIPT="$(realpath "$0")"
BASEDIR="$(dirname "${SCRIPT}")"

IN_DIR="${BASEDIR}/proto"
OUT_DIR="${BASEDIR}"

pushd "${BASEDIR}" >> /dev/null || exit 1

python3 -m grpc_tools.protoc \
    -I"./proto" \
    --python_out=. \
    --grpc_python_out=. \
    --pyi_out=. \
    ./proto/*.proto

# as of Ubuntu20.04/Python3.8.10, gRPC improperly sets relative imports for *_grpc.py files
# so, we're modifying them in place here
for file in ./*pb2*.py; do
    # for lines containing "import <modulename> as "
    # replace 'import' with 'from . import'
    sed -i -e  '/^import [A-Za-z0-9_]* as/ s/import/from . import/g' "${file}"
done

popd >> /dev/null || exit 1