# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import Topic_pb2 as Topic__pb2


class TopicStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AdvertiseTopic = channel.unary_unary(
                '/core.Topic/AdvertiseTopic',
                request_serializer=Topic__pb2.TopicDefinition.SerializeToString,
                response_deserializer=Topic__pb2.AdvertiseConfirmation.FromString,
                )
        self.SubscribeTopic = channel.unary_unary(
                '/core.Topic/SubscribeTopic',
                request_serializer=Topic__pb2.TopicDefinition.SerializeToString,
                response_deserializer=Topic__pb2.Confirmation.FromString,
                )


class TopicServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AdvertiseTopic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTopic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TopicServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AdvertiseTopic': grpc.unary_unary_rpc_method_handler(
                    servicer.AdvertiseTopic,
                    request_deserializer=Topic__pb2.TopicDefinition.FromString,
                    response_serializer=Topic__pb2.AdvertiseConfirmation.SerializeToString,
            ),
            'SubscribeTopic': grpc.unary_unary_rpc_method_handler(
                    servicer.SubscribeTopic,
                    request_deserializer=Topic__pb2.TopicDefinition.FromString,
                    response_serializer=Topic__pb2.Confirmation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.Topic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Topic(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AdvertiseTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.Topic/AdvertiseTopic',
            Topic__pb2.TopicDefinition.SerializeToString,
            Topic__pb2.AdvertiseConfirmation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.Topic/SubscribeTopic',
            Topic__pb2.TopicDefinition.SerializeToString,
            Topic__pb2.Confirmation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
